### PR TITLE
fix: reopen deliberately closed websocket if subscriptions still exist

### PR DESCRIPTION
**Pull request by steveluscher**
#### Problem

Imagine that the client expects certain subscriptions to be alive. When a websocket is closed deliberately (ie. with a `CLOSE_NORMAL` code) those subscriptions die and are never reestablished, even when the socket reconnects. This is because we never clear out the now-disposed _server_ subscription ids.

#### Summary of Changes

Whether a websocket closed because of a connection interruption, or because the developer closed it explicitly, we now reopen the socket if the client still expects certain subscriptions to be alive.

### CODE REVIEW

**Comment by steveluscher** [comment]
@jstarry, does this look right to you? I came across this during a general revamp of the subscriptions tracker. I confirmed that the test added in this PR fails against the current code.

**Comment by jstarry** [comment]
We only explicitly close if there are no active subscriptions. It's possible a new subscription comes while the socket is closing but that will trigger a new connection and only once we are connected will we try to make a subscribe call. So I think the current code behaves well enough as is. Check how `_rpcWebSocketConnected` is updated to follow the flow

**Comment by steveluscher** [comment]
Oh, totally, but we _also_ leak all of these private members out to the world. Someone can literally just write this:

```
connection._rpcWebSocket.emit('close', 1000);
```

…and boom, it's closed.

Wherever it's possible to do, guaranteed someone is doing it. I'm wondering if this could explain some of the stories that Brian Long was telling me about projects having their socket go down and never try to reconnect.

Side note, we should start compiling private members to actually be private.

**Comment by jstarry** [comment]
Your argument is a slippery slope because people can do whatever they want to private members to cause problems. I think we should focus on problems that we know are happening and are reproducible so that we know that we're fixing the right thing.

**Pull request closed without merging**
